# Site settings
title: 枯藤老树昏鸦 小桥流水人家
email: withliyh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    科技让生活更美好
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://withliyh.github.io" # the base hostname & protocol for your site
permalink: /blog/:title
#twitter_username: jekyllrb
github_username:  withliyh

# Build settings
markdown: redcarpet
excerpt_separator: ""
